# Generated by Django 3.1.5 on 2021-01-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='manager',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='none.png', null=True, upload_to='profile_pic/'),
        ),
    ]
