# Generated by Django 3.1.5 on 2021-01-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0002_leave_resion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='ending_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='half_day',
            field=models.CharField(choices=[('select ', 'Select'), ('first_half', 'First Half'), ('second_half', 'Second Half')], default='Select', max_length=225),
        ),
        migrations.AlterField(
            model_name='leave',
            name='starting_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
